upgraded phantomjs install until I got it to work and install the right proper version automatically

diff --git a/install_phantomjs_casperjs_without_git b/install_phantomjs_casperjs_without_git
--- a/install_phantomjs_casperjs_without_git
+++ b/install_phantomjs_casperjs_without_git
@@ -214,6 +214,184 @@ phantomjs_install() {
 } # end phantomjs_install
 
 
+
+install_phantom_js_using_npm() {
+
+    local phantomjs_version=""
+    if [[ ! -z "${1+x}"  ]] ; then  # check if a variable is set and not empty
+        phantomjs_version="${1}"
+    fi
+
+    export NVM_DIR="/home/vagrant/.nvm"
+    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
+
+    if [ ! -z "${phantomjs_version}" ] ;  then
+    {
+        echo "        # Installing PhantomJS version ${phantomjs_version}. "
+        npm -g install phantomjs@"${phantomjs_version}"
+        wait
+    }
+    else
+    {
+        phantomjs_version="LASTEST"
+        echo "        # Installing ${phantomjs_version} PhantomJS |  phantomjs-prebuilt; phantomjs2;"
+
+        npm -g install phantomjs-prebuilt;
+        wait
+        npm -g install phantomjs2;
+        wait
+    }
+    fi
+
+    echo  "PhantomJS ${phantomjs_version} version install complete";
+} # end phantomjs_install
+
+obtain_phantom_name_based_on_operating_system() {
+    local phantomjs_version=""
+    if [ ! -z "${1}" ] ;  then
+        phantomjs_version="${1}"
+    fi
+
+    # check operation systems
+    if [[ "$(uname)" == "Darwin" ]] ; then
+      # Do something under Mac OS X platform
+        [[ "$(uname -m)" == "x86_64" ]] && echo "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-${phantomjs_version}-macosx.zip"
+        [[ "$(uname -m)" == "i686"   ]] && echo "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-${phantomjs_version}-macosx.zip"
+    elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]] ; then
+      # Do something under GNU/Linux platform
+      # ubuntu lsb_release -i | sed 's/Distributor\ ID://g' = \tUbuntu\n
+        [[ "$(uname -i)" == "x86_64" ]] && echo "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-${phantomjs_version}-linux-x86_64.tar.bz2"
+        [[ "$(uname -i)" == "i686"   ]] && echo "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-${phantomjs_version}-linux-i686.tar.bz2"
+    elif [[ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]] ; then
+      # Do something under Windows NT platform
+      echo "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-${phantomjs_version}-windows.zip"
+      # nothing here
+    fi
+}
+
+install_phantom_js_using_download() {
+    local phantomjs_version=""
+    if [ ! -z "${1}" ] ;  then
+        phantomjs_version="${1}"
+    fi
+
+    if [[ -z "${NODE_VERSION}" ]] ;  then
+        failed "I am missing NODE_VERSION var"
+    fi
+
+    CURRENT_NODE_HOME="${HOME}"/.nvm/versions/node/"${NODE_VERSION}"/
+
+    if [[ "${CURRENT_NODE_HOME}" == "${HOME}/.nvm/versions/node//" ]] ;  then
+        failed "I am missing CURRENT_NODE_HOME var"
+    fi
+
+    cd "${CURRENT_NODE_HOME}"lib/node_modules;
+
+
+    if [  -z "${phantomjs_version}" ] ; then
+    {
+        # Get latest version
+        PAGE=$(wget https://bitbucket.org/ariya/phantomjs/downloads/?tab=downloads -q -O -)
+        phantomjs_version=$(echo $PAGE | sed -n 's/.*href="\([^"]*\).*/\1/p'  | grep phantomjs- | sed 's/[^0-9.]*\([0-9.]*\).*/\1/' | sort -rn | uniq | sed '/^\s*$/d' | head -1)
+
+    }
+    fi
+
+    # Download  git repo using GIT -- DISABLED - its slower than unziping
+        # Deprecated but insteresting to know how to CHECKOUT by TAG name. Leaving for Reference
+        #    if [ ! -z "${phantomjs_version}" ] && type_function_exists "git" ;  then
+        #    {
+        #        echo "        # Installing PhantomJS version ${phantomjs_version}. "
+        #        git clone https://github.com/ariya/phantomjs.git phantomjs
+        #        cd phantomjs
+        #        wait
+        #        git checkout -b test remotes/origin/"${phantomjs_version}"  # How to do a “git checkout -b <branchname>” from a remote tag REF: https://stackoverflow.com/questions/7572647/how-to-do-a-git-checkout-b-branchname-from-a-remote-tag
+        #        wait
+        #        cd ..
+        #        wait
+        #    }
+        #    el
+
+    # Download  git repo using ZIP
+        echo "        # Installing PhantomJS version ${phantomjs_version}  |"
+        wget https://github.com/ariya/phantomjs/zipball/"${phantomjs_version}"
+        wait
+        unzip -o "${phantomjs_version}"
+        wait
+        [ -d phantomjs ] &&  rm -rf phantomjs
+        mv *phantomjs* phantomjs;
+        # clean up
+        rm "${phantomjs_version}"
+
+    # Download precompiled BINARY
+        # expected: we are here "${CURRENT_NODE_HOME}"lib/node_modules/
+        DONWLOAD_FILE_NAME=$(obtain_phantom_name_based_on_operating_system "${phantomjs_version}")
+        # expected something like : phantomjs-2.1.1-linux-x86_64.tar.bz2
+        # expected something like : phantomjs-2.1.1-macosx.zip
+
+        wget "${DONWLOAD_FILE_NAME}"
+        if (( ! $? == 0 )); then
+        {
+            failed "I could not download: ${DONWLOAD_FILE_NAME}"
+        }
+        fi
+        wait
+        if [[ "${DONWLOAD_FILE_NAME}" == *".zip" ]] ; then
+        {
+            unzip -o phantomjs-*
+        }
+        elif [[ "${DONWLOAD_FILE_NAME}" == *".bz2" ]] ; then
+        {
+            tar xvjf phantomjs-*
+        }
+        else
+        {
+            failed "I don't know how to unzip/untar this file: ${DONWLOAD_FILE_NAME}"
+        }
+        fi
+        # expected: we are here "${CURRENT_NODE_HOME}"lib/node_modules/
+        cp -rvf phantomjs-*/bin phantomjs/
+        cp -rvf phantomjs-*/examples phantomjs/
+        # clean up
+        rm -rvf phantomjs-*
+
+        cd "${CURRENT_NODE_HOME}"bin;
+        [[ -L phantomjs ]] && unlink phantomjs
+        ln -s "${CURRENT_NODE_HOME}"lib/node_modules/phantomjs/bin/phantomjs phantomjs;
+
+    #    #### Deprecated Just getting master.
+    #
+    #        phantomjs_version="LASTEST"
+    #        echo "        # Installing ${phantomjs_version} PhantomJS |  # Downloading PhantomJS! Latest Dev Version;"
+    #        wget https://github.com/ariya/phantomjs/zipball/master;
+    #        wait
+    #        unzip -o master;
+    #        wait
+    #        mv *phantomjs* phantomjs;   # RENAME
+    #        # clean up
+    #        rm master
+    #
+    #        # build binary phantom manually REF: http://phantomjs.org/build.html
+    #        cd phantomjs
+    #        sudo apt-get install -y build-essential g++ flex bison gperf ruby perl \
+    #          libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev \
+    #          libpng-dev libjpeg-dev python libx11-dev libxext-dev
+    #
+    #        python build.py
+    #        build.sh
+    #
+    #
+    #
+    #        cd "${CURRENT_NODE_HOME}"bin;
+    #        [[ -L phantomjs ]] && unlink phantomjs
+    #        ln -s "${CURRENT_NODE_HOME}"lib/node_modules/phantomjs/bin/phantomjs phantomjs;
+
+
+
+    echo 'PhantomJS Installation Complete';
+
+} # end casper_install
+
 casper_install() {
     local casper_version=""
     if [ ! -z "${1}" ] ;  then
@@ -221,22 +399,22 @@ casper_install() {
     fi
 
     if [[ -z "${NODE_VERSION}" ]] ;  then
-        fail "I am missing NODE_VERSION var"
+        failed "I am missing NODE_VERSION var"
     fi
 
     CURRENT_NODE_HOME="${HOME}"/.nvm/versions/node/"${NODE_VERSION}"/
 
     if [[ "${CURRENT_NODE_HOME}" == "${HOME}/.nvm/versions/node//" ]] ;  then
-        fail "I am missing CURRENT_NODE_HOME var"
+        failed "I am missing CURRENT_NODE_HOME var"
     fi
 
-    cd $CURRENT_NODE_HOME/lib/node_modules;
+    cd "${CURRENT_NODE_HOME}"lib/node_modules;
 
     if [ ! -z "${casper_version}" ] ;  then
     {
         echo "        # Installing CasperJS version ${casper_version}. "
         git clone https://github.com/casperjs/casperjs.git casperjs
-        cd casperjs-casperjs-"${casper_version}"
+        cd casperjs
         wait
         git checkout -b test remotes/origin/"${casper_version}"  # How to do a “git checkout -b <branchname>” from a remote tag REF: https://stackoverflow.com/questions/7572647/how-to-do-a-git-checkout-b-branchname-from-a-remote-tag
         wait
@@ -246,10 +424,10 @@ casper_install() {
     else
     {
         casper_version="LASTEST"
-        echo "        # Installing ${casper_version} CasperJS ! |  # Downloading CasperJS! Latest Dev Version;"
+        echo "        # Installing ${casper_version} CasperJS |  # Downloading CasperJS. Latest Dev Version;"
         wget https://github.com/n1k0/casperjs/zipball/master;
         wait
-        unzip master;
+        unzip -o master;
         wait
         mv *casperjs* casperjs;   # RENAME
         # clean up
@@ -258,8 +436,9 @@ casper_install() {
     }
     fi
 
-    cd "${CURRENT_NODE_HOME}"/bin;
-    ln -s "${CURRENT_NODE_HOME}"/lib/node_modules/casperjs/bin/casperjs casperjs;
+    cd "${CURRENT_NODE_HOME}"bin;
+    [[ -L casperjs ]] && unlink casperjs
+    ln -s "${CURRENT_NODE_HOME}"lib/node_modules/casperjs/bin/casperjs casperjs;
     source_nvm
 
     echo 'CasperJS Installation Complete';
@@ -378,7 +557,8 @@ check_wget_or_curl_are_installed
 
 nvm_install
 node_install "${node_version}"
-phantomjs_install "${phantomjs_version}"
+#phantomjs_install "${phantomjs_version}"
+install_phantom_js_using_download "${phantomjs_version}"
 casper_install "${casper_version}"
 
 verify_installations
