updated struct testing call to install_phantomjs_casperjs_without_git without sudo

diff --git a/install_phantomjs_casperjs_without_git b/install_phantomjs_casperjs_without_git
--- a/install_phantomjs_casperjs_without_git
+++ b/install_phantomjs_casperjs_without_git
@@ -11,13 +11,13 @@
 
 
 
-                                        ######## ##     ## ##    ##  ######  ######## ####  #######  ##    ##  ######
-                                        ##       ##     ## ###   ## ##    ##    ##     ##  ##     ## ###   ## ##    ##
-                                        ##       ##     ## ####  ## ##          ##     ##  ##     ## ####  ## ##
-                                        ######   ##     ## ## ## ## ##          ##     ##  ##     ## ## ## ##  ######
-                                        ##       ##     ## ##  #### ##          ##     ##  ##     ## ##  ####       ##
-                                        ##       ##     ## ##   ### ##    ##    ##     ##  ##     ## ##   ### ##    ##
-                                        ##        #######  ##    ##  ######     ##    ####  #######  ##    ##  ######
+######## ##     ## ##    ##  ######  ######## ####  #######  ##    ##  ######
+##       ##     ## ###   ## ##    ##    ##     ##  ##     ## ###   ## ##    ##
+##       ##     ## ####  ## ##          ##     ##  ##     ## ####  ## ##
+######   ##     ## ## ## ## ##          ##     ##  ##     ## ## ## ##  ######
+##       ##     ## ##  #### ##          ##     ##  ##     ## ##  ####       ##
+##       ##     ## ##   ### ##    ##    ##     ##  ##     ## ##   ### ##    ##
+##        #######  ##    ##  ######     ##    ####  #######  ##    ##  ######
 
 
 
@@ -29,7 +29,54 @@
 ### PROCEDURTES, DEFS, FUNCTIONS: WHATEVERS ####
 #                                              #
 #                                              #
+#
+#
+# - - -  struct_testing no sudo - - -  START
+#
+#
+# DEBUG=1
+# REMOVECACHE=1
+export THISSCRIPT
+typeset -gr THISSCRIPT="$0"
+(( DEBUG ))  && echo "${THISSCRIPT}"
+export THISFOLDER
+typeset -gr THISFOLDER="$(dirname "$0")"
+(( DEBUG ))  && echo "${THISFOLDER}"
 
+if ( ! command -v nproc >/dev/null 2>&1; ) ; then {
+  export CPU_COUNT
+  typeset -gr CPU_COUNT="$(nproc)"
+  (( DEBUG ))  && echo "${CPU_COUNT}"
+}
+fi
+
+export THISSCRIPTCOMPLETEPATH
+typeset -gr THISSCRIPTCOMPLETEPATH="$(basename "$0")"   # § This goes in the FATHER-MOTHER script
+export _err
+typeset -i _err=0
+export USER_HOME="$HOME"
+export SUDO_USER="$USER"
+
+load_struct_testing_wget(){
+    local provider="$HOME/_/clis/execute_command_intuivo_cli/struct_testing"
+    # shellcheck disable=SC1090
+    [   -e "${provider}"  ] && source "${provider}" && echo "Loaded locally"
+    [ ! -e "${provider}"  ] && eval """$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/struct_testing -O -  2>/dev/null )"""   # suppress only wget download messages, but keep wget output for variable
+    ( ( ! command -v passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 69; )
+} # end load_struct_testing_wget
+load_struct_testing_wget
+
+enforce_variable_with_value USER_HOME "${USER_HOME}"
+enforce_variable_with_value SUDO_USER "${SUDO_USER}"
+
+enforce_variable_with_value THISSCRIPT "${THISSCRIPT}"
+enforce_variable_with_value THISFOLDER "${THISFOLDER}"
+enforce_variable_with_value THISSCRIPTCOMPLETEPATH "${THISSCRIPTCOMPLETEPATH}"
+#
+#
+# - - -  struct_testing no sudo - - -  END
+#
+#
 
 load_colors_script_name_and_break_trap() {
 
@@ -48,20 +95,6 @@ load_colors_script_name_and_break_trap() {
 
     THISSCRIPTNAME=`basename "$0"`
 } # end load_colors_script_name_and_break_trap
-
-
-load_struct_testing(){
-    EXECOMCLI=$(wget --quiet --no-check-certificate https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/struct_testing -O -  2>/dev/null )   # suppress only curl download messages, but keep curl output for variable
-    eval """${EXECOMCLI}"""
-    #echo """${EXECOMCLI}""" | grep verify_installed_version
-    #echo """${EXECOMCLI}"""
-    #exit 130;
-
-    ( ( ! command -v passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 130; )
-
-    # verify
-} # end function load_struct_testing
-
 
 type_function_exists() {
   type "$1" > /dev/null 2>&1
@@ -487,7 +520,7 @@ verify_installations() {
 display_help() {
     echo -e "
 
-${GRAYEDOUT} ${THISSCRIPTNAME} Installs nvm, npm, phantomjs and caspterjs
+${CERO} ${THISSCRIPTNAME} Installs nvm, npm, phantomjs and caspterjs
 
     Usage
 
@@ -500,6 +533,7 @@ ${GRAYEDOUT} ${THISSCRIPTNAME} Installs nvm, npm, phantomjs and caspterjs
 
          ${THISSCRIPTNAME}  1.9.8    7.7.2    1.1.4   ---> will install nvm, node version v7.7.2, and phantomjs version 1.9.8, and caspterjs version 1.1.4
     "
+
 } # end display_help
 
 
@@ -551,7 +585,6 @@ fi
 
 load_colors_script_name_and_break_trap
 display_help
-load_struct_testing
 
 check_wget_or_curl_are_installed
 
