updated project sample view

diff --git a/project_list_prepare b/project_list_prepare
--- a/project_list_prepare
+++ b/project_list_prepare
@@ -5,6 +5,8 @@
 #
 #
 # Helper For testing downloading a list of subfolders
+    struct_testing
+    execute_command
 
 load_execute_commands_wget(){
         local URL=""
@@ -14,8 +16,6 @@ load_execute_commands_wget(){
         [   -d "${cached_directory}" ] &&  provider="file://${cached_directory}"
         [ ! -d "${cached_directory}" ] &&  provider="https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/"
         local BASH_SCRIPTS="
-    struct_testing
-    execute_command
     check_system_requirements
     "
     #execute_command
@@ -484,7 +484,7 @@ process_list_repos(){
 	    [ -z "${LINE}" ] && continue  # if not empty
 	    # if [ ! -z "${LINE}" ] ; then # if not empty
 	    # {
-	    	if [[ -z "${LINE}" == *":"* ]] ; then # if has **abc:abc**
+	    	if [ -z "${LINE}" = *"|"* ] ; then 
 	    	{
 	    		REPO_NAME=$(echo "${LINE}" | cut -d':' -f2)
 	    		continue
@@ -552,24 +552,25 @@ remove_list_repos(){
 #
 # @author Zeus Intuivo <zeus@intuivo.com>
 #
-load_project_list_prepare_wget(){
-    local provider="/_/clis/ruby_intuivo_cli/project_list_prepare"
-    [   -e "${provider}"  ] && source "${provider}"
-    [ ! -e "${provider}"  ] && eval """$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/ruby_intuivo_cli/master/project_list_prepare -O -  2>/dev/null )"""   # suppress only wget download messages, but keep wget output for variable
-    ( ( ! command -v type passed >/dev/null 2>&1;) && echo -e "\n \n  ERROR! Loading project_list_prepare \n \n " && exit 69; )
-}
+#
+# load_project_list_prepare_wget(){
+#     local provider="/_/clis/ruby_intuivo_cli/project_list_prepare"
+#     [   -e "${provider}"  ] && source "${provider}"
+#    [ ! -e "${provider}"  ] && eval """$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/ruby_intuivo_cli/master/project_list_prepare -O -  2>/dev/null )"""   # suppress only wget download messages, but keep wget output for variable
+#    ( ( ! command -v type passed >/dev/null 2>&1;) && echo -e "\n \n  ERROR! Loading project_list_prepare \n \n " && exit 69; )
+# }
 # end load_project_list_prepare_wget
-load_project_list_prepare_wget
-
-REPOS="
-
-1:repository
-repo_name_1_inside_1
-repon_name_2_inside_1
-
-2:repository_2
-repo_name_inside_2
-repon_name_2_inside_2
-
-"
-process_list_repos "${REPOS}"
+# load_project_list_prepare_wget
+#
+# REPOS="
+#
+# 1:repository
+# repo_name_1_inside_1
+# repon_name_2_inside_1
+#
+# 2:repository_2
+# repo_name_inside_2
+# repon_name_2_inside_2
+#
+# "
+# process_list_repos "${REPOS}"
